import jsPDF from 'jspdf';
import type { BuildingFloorGeometry } from '@/lib/types/building-geometry';

/**
 * Export floor plan directly to PDF with professional formatting
 */
export async function exportToPDFDirect(
    geometry: BuildingFloorGeometry,
    scaleFtPerUnit: number,
    buildingName: string,
    buildingDimensions?: { width: number; depth: number }
) {
    const { vertices, segments } = geometry;

    if (vertices.length === 0) {
        alert('Cannot export an empty floor plan');
        return;
    }

    // Calculate bounding box
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    vertices.forEach((v) => {
        minX = Math.min(minX, v.x);
        minY = Math.min(minY, v.y);
        maxX = Math.max(maxX, v.x);
        maxY = Math.max(maxY, v.y);
    });

    const width = Math.max((maxX - minX) * scaleFtPerUnit, 10);
    const height = Math.max((maxY - minY) * scaleFtPerUnit, 10);

    // Create PDF (Letter size: 8.5" x 11")
    const pdf = new jsPDF({
        orientation: width > height ? 'landscape' : 'portrait',
        unit: 'in',
        format: 'letter',
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 0.5;
    const drawableWidth = pageWidth - 2 * margin;
    const drawableHeight = pageHeight - 2 * margin - 1; // Reserve space for title
    // Calculate scale to fit
    const scaleX = drawableWidth / width;
    const scaleY = drawableHeight / height;
    const pdfScale = Math.min(scaleX, scaleY, 1); // Don't scale up

    // Center the drawing
    const offsetX = margin + (drawableWidth - width * pdfScale) / 2;
    const offsetY = margin + 1 + (drawableHeight - height * pdfScale) / 2;

    // Title
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.text(buildingName + ' - Floor Plan', pageWidth / 2, margin + 0.3, { align: 'center' });

    // Subtitle with dimensions
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    if (buildingDimensions) {
        pdf.text(
            `${buildingDimensions.width}' × ${buildingDimensions.depth}' | Scale: 1:${Math.round(1 / (scaleFtPerUnit * pdfScale))}`,
            pageWidth / 2,
            margin + 0.6,
            { align: 'center' }
        );
    }

    // Draw grid (light gray)
    pdf.setDrawColor(220, 220, 220);
    pdf.setLineWidth(0.005);
    const gridSpacing = 5 * scaleFtPerUnit * pdfScale; // 5 ft grid
    for (let x = 0; x <= width * pdfScale; x += gridSpacing) {
        pdf.line(
            offsetX + x,
            offsetY,
            offsetX + x,
            offsetY + height * pdfScale
        );
    }
    for (let y = 0; y <= height * pdfScale; y += gridSpacing) {
        pdf.line(
            offsetX,
            offsetY + y,
            offsetX + width * pdfScale,
            offsetY + y
        );
    }

    // Draw walls (black, thick)
    pdf.setDrawColor(0, 0, 0);
    segments.forEach((seg) => {
        const v1 = vertices.find((v) => v.id === seg.a);
        const v2 = vertices.find((v) => v.id === seg.b);

        if (v1 && v2) {
            const x1 = offsetX + (v1.x - minX) * scaleFtPerUnit * pdfScale;
            const y1 = offsetY + (v1.y - minY) * scaleFtPerUnit * pdfScale;
            const x2 = offsetX + (v2.x - minX) * scaleFtPerUnit * pdfScale;
            const y2 = offsetY + (v2.y - minY) * scaleFtPerUnit * pdfScale;

            // Set line width based on wall thickness (converted to PDF inches)
            const thicknessFt = seg.thickness || 0.5;
            const thicknessInPdf = thicknessFt * pdfScale;
            pdf.setLineWidth(Math.max(thicknessInPdf, 0.01));

            pdf.line(x1, y1, x2, y2);

            // Add dimension label
            const midX = (x1 + x2) / 2;
            const midY = (y1 + y2) / 2;
            const length = Math.sqrt(
                Math.pow((v2.x - v1.x) * scaleFtPerUnit, 2) +
                Math.pow((v2.y - v1.y) * scaleFtPerUnit, 2)
            );

            pdf.setFontSize(8);
            pdf.setTextColor(100, 100, 100);
            pdf.text(`${length.toFixed(1)}'`, midX, midY - 0.05, { align: 'center' });
        }
    });

    // Draw vertices (blue dots)
    pdf.setFillColor(0, 102, 204);
    vertices.forEach((v) => {
        const x = offsetX + (v.x - minX) * scaleFtPerUnit * pdfScale;
        const y = offsetY + (v.y - minY) * scaleFtPerUnit * pdfScale;
        pdf.circle(x, y, 0.03, 'F');
    });

    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
        `Generated by Comet Wall Designer | ${new Date().toLocaleDateString()}`,
        pageWidth / 2,
        pageHeight - margin + 0.2,
        { align: 'center' }
    );

    // Save
    pdf.save(`${buildingName.replace(/\s+/g, '_')}_floor_plan.pdf`);
}
